#pragma once

#include "System/engine.h"
#include "System/mainengine.h"
#include "System/positionnable.h"
#include "System/material.h"
#include "System/vector-all.h"
#include "System/Shape/shape.h"
#include "System/Shape/circle.h"
#include "System/Shape/polygon.h"

#include "System/Provider/positionprovider.h"
#include "System/Provider/componentprovider.h"
#include "System/Provider/displaycomponentprovider.h"
#include "System/Provider/callbackcomponentprovider.h"
#include "System/Provider/callbackdisplaycomponentprovider.h"
#include "System/Provider/callbackpositionprovider.h"
#include "System/Provider/zerocomponentprovider.h"
#include "System/Provider/zerodisplaycomponentprovider.h"
#include "System/Provider/zeropositionprovider.h"

#include "System/Traits/position.h"
#include "System/Traits/vertex.h"
#include "System/Traits/angle.h"
#include "System/Traits/radius.h"
